name: Chromatic Action
author: Chroma
description: "Publishes your Storybook to Chromatic and runs visual tests"

inputs: 
  projectToken: 
    description: "Your chromatic/chroma project token"
  buildScriptName: 
    description: "The npm script that builds your Storybook [build-storybook]"
  doNotStart: 
    description: "Do not attempt to start or build; use if your Storybook is already running"
  exec: 
    description: "Alternatively, a full command to run to start your storybook"
  scriptName: 
    description: "The npm script that starts your Storybook [storybook]"
  storybookBuildDir: 
    description: "Provide a directory with your built storybook; use if you have already built your storybook"
  storybookCa: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookCert: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookHttps: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookKey: 
    description: "Use if Storybook is running on https (auto detected from -s, if set)"
  storybookPort: 
    description: "What port is your Storybook running on (auto detected from -s, if set)"
  storybookUrl: 
    description: "Storybook is already running at (external) url (implies -S)"

runs: 
  main: main.js
  using: node12
